---
title: "HW06"
author: "Zach White"
date: "April 4, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(expm)
```

# Problem 3

## Part B
```{r}
x1 = c(0,1/2,1/2,0,0)
x2 = c(1/3,0,0,1/3,0)
x4 = c(1/3,0,0,1/3,0)
x5 = c(0,1/3,1/3,0,1/3)
x6 = c(0,0,0,1/2,0)

x3 = c(0,1/3,0,0,1/2)
x7 = c(0,0,1/3,0,0)

R = cbind(x3,x7)

Q = rbind(x1,x2,x4,x5,x6)

I.Q = diag(1,5) - Q
inv.I.Q = solve(I.Q)
inv.I.Q %*% rep(1,5)
inv.I.Q %*% R
```

# Problem 4
```{r}
x1 = c(1,0,0,0,0,0,0,0,0,0)
x2 = c(-1/2,1,0,0,0,0,0,0,0,0)
x3 = c(-1/3,-1/3,1,0,0,0,0,0,0,0)
x4 = c(-1/4,-1/4,-1/4,1,0,0,0,0,0,0)
x5 = c(-1/5,-1/5,-1/5,-1/5,1,0,0,0,0,0)
x6 = c(-1/6,-1/6,-1/6,-1/6,-1/6,1,0,0,0,0)
x7 = c(-1/7,-1/7,-1/7,-1/7,-1/7,-1/7,1,0,0,0)
x8 = c(-1/8,-1/8,-1/8,-1/8,-1/8,-1/8,-1/8,1,0,0)
x9 = c(-1/9,-1/9,-1/9,-1/9,-1/9,-1/9,-1/9,-1/9,1,0)
x10 = c(-1/10,-1/10,-1/10,-1/10,-1/10,-1/10,-1/10,-1/10,-1/10,1)

I.Q = rbind(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10)
solve(I.Q)
```

# Problem 5

## Part A
```{r}
x1 = c(0,1/2,0,1/2,0,0,0)
x2 = c(1/3,0,1/3,0,1/3,0,0)
x3= c(0,1/2,0,0,1/2,0,0)
x4 = c(1/3,0,0,0,1/3,0,1/3)
x5 = c(0,1/3,0,1/3,0,1/3,0)
x6 = c(0,0,1/2,0,1/2,0,0)
x7 = c(0,0,0,0,0,0,1)

P = rbind(x1,x2,x3,x4,x5,x6,x7)
P %^% 100
```

## Part B
This is under my formulation for the problem because I wasn't aware of the last, qualifyin statement saying that the stat before the exit wasn't an absorption.  I take that state as absorbing and then in my next simulation.  I do it according to the way it should be.
```{r}
n.samps = 10000
food.before = NULL
for(j in 1:n.samps){
  chain = NULL
  chain[1] = 4
  i = 1
  while(chain[i] != 7){
    if(chain[i] == 1){chain[i+1] = sample(c(2,4),1)}
    else if(chain[i] == 2){chain[i+1] = sample(c(1,3,5),1)}
    else if(chain[i] == 3){chain[i+1] = sample(c(2,6),1)}
    else if(chain[i] == 4){chain[i+1] = sample(c(1,5,7),1)}
    else if(chain[i] == 5){chain[i+1] = sample(c(4,2,6),1)}
    else if(chain[i] == 6){chain[i+1] = sample(c(3,5),1)}
    #if(chain[i] == 7){chain[i+1] = sample(c(4,8))}
    if(chain[i] != 7){
      i = i+1
    }
  }
  if(is.element(3,chain)){
    food.before[j] = 1
  }  
  else{
    food.before[j] = 0
  }
}
chain
mean(food.before)
```

```{r}
n.samps = 10000
food.before = NULL
for(j in 1:n.samps){
  chain = NULL
  chain[1] = 4
  i = 1
  while(chain[i] != 8){
    if(chain[i] == 1){chain[i+1] = sample(c(2,4),1)}
    else if(chain[i] == 2){chain[i+1] = sample(c(1,3,5),1)}
    else if(chain[i] == 3){chain[i+1] = sample(c(2,6),1)}
    else if(chain[i] == 4){chain[i+1] = sample(c(1,5,7),1)}
    else if(chain[i] == 5){chain[i+1] = sample(c(4,2,6),1)}
    else if(chain[i] == 6){chain[i+1] = sample(c(3,5),1)}
    else if(chain[i] == 7){chain[i+1] = sample(c(4,8),1)}
    if(chain[i] != 8){
      i = i+1
    }
  }
  if(is.element(3,chain)){
    food.before[j] = 1
  }  
  else{
    food.before[j] = 0
  }
}
chain
mean(food.before)
```